### ISSUE TITLE
share 

### ISSUE THREAD

**Issue by ketingli1** [ketingli1/ketingli1.github.io#1]

**Comment by ketingli1** [comment]
https://plugins.jetbrains.com/plugin/1347-scala/versions

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3508030/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

2019年8月16日12:04:02： attach

**Comment by ketingli1** [comment]
spark.executor.extraClassPath=/home/hadoop/wzq_workspace/lib/*
spark.driver.extraClassPath=/home/hadoop/wzq_workspace/lib/*

**Comment by iwuming** [comment]
ssh-keygen -t rsa -C "zhaosla@yutong.com"

**Comment by ketingli1** [comment]
/home/hadoop/spark-2.2.2-bin-hadoop2.7/bin/spark-submit \
--class com.icongtai.zebra.db.dwd.GpsDivideJourneyApplication \
--master yarn \
--deploy-mode client \
--driver-memory 1g \
--driver-cores 2 \
--num-executors 10 \
--executor-cores 2  \
--executor-memory 4g \
/home/hadoop/resource/driver-behavior-bigdata-source-1.0-SNAPSHOT.jar

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3508221/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3508225/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3509097/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3511830/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3511860/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3512031/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3512046/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3512066/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3512080/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3512085/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3512089/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3512103/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3513820/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3513943/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514006/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514039/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514162/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514170/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514189/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514197/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514208/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514227/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514253/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514278/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514458/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514484/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514504/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3514648/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3515560/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3523314/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[resource.zip](https://github.com/ketingli1/ketingli1.github.io/files/3523332/resource.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3524941/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3525007/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3525033/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3525059/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3525119/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)

**Comment by ketingli1** [comment]
[driver-behavior-bigdata-source-1.0-SNAPSHOT.zip](https://github.com/ketingli1/ketingli1.github.io/files/3525165/driver-behavior-bigdata-source-1.0-SNAPSHOT.zip)
