### ISSUE TITLE
outputData

### ISSUE THREAD

**Issue by ketingli1** [ketingli1/ketingli1.github.io#6]
[cd178aab-1d28-4806-a4f2-7369ae8f285c.zip](https://github.com/ketingli1/ketingli1.github.io/files/3546191/cd178aab-1d28-4806-a4f2-7369ae8f285c.zip)

**Comment by ketingli1** [comment]
AFAD0D8532A84E26B49C28790FC06719

**Comment by xingopq** [comment]
[all2.txt](https://github.com/ketingli1/ketingli1.github.io/files/3550500/all2.txt)

**Comment by xingopq** [comment]
[all.txt](https://github.com/ketingli1/ketingli1.github.io/files/3550517/all.txt)

**Comment by xingopq** [comment]
use yutongdriverbeh;
update event_detail_0612 set event_id = 'A3E4D51E8E0F44359831EBF3FDC99EC2_20190821161801_19003402';
update event_detail_0613 set event_id = 'A3E4D51E8E0F44359831EBF3FDC99EC2_20190821161801_19003402';

**Comment by ketingli1** [comment]
E23838C7F64A42758BFE5B34A9B220AC

**Comment by xingopq** [comment]
[all.txt](https://github.com/ketingli1/ketingli1.github.io/files/3550599/all.txt)

**Comment by xingopq** [comment]
[auto_violation_detail.txt](https://github.com/ketingli1/ketingli1.github.io/files/3554219/auto_violation_detail.txt)

**Comment by xingopq** [comment]
[auto_violation_detail.txt](https://github.com/ketingli1/ketingli1.github.io/files/3554292/auto_violation_detail.txt)

**Comment by ketingli1** [comment]
RM000000000000021

**Comment by xingopq** [comment]
[driver.txt](https://github.com/ketingli1/ketingli1.github.io/files/3562049/driver.txt)
